DELETE http://localhost:3001/api/logout
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR5bmFtb0BnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjg0NTExODgxLCJleHAiOjE2ODQ1MTU0ODF9.dF_7cB0BKfu69pa1Rn4Tk6ZLSlD4gr3J4-lisLtYIaA
