POST http://localhost:3001/api/blogs
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR5bmFtb0BnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjg0NDI5NzYyLCJleHAiOjE2ODQ0MzMzNjJ9.c8kyO7kmiB4jZBP6hNDcvqP6xdhwhXME_H3vQ5cUsbU

{
    "author":"elias hietanen",
    "url":"www.myblogs.com",
    "title":"relational database",
    "likes":5,
    "year_written": 1992
}

###
POST http://localhost:3001/api/blogs
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR5bmFtb0BnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjg0NDM2NjI2LCJleHAiOjE2ODQ0NDAyMjZ9.X4-0e4VNZTsZAVndV4ux_kUyhjq6hJRE3PrL_S7kabM
content-type: application/json

{
    "author":"elias hietanen",
    "url":"www.blogspots.com",
    "title":"containers",
    "likes":1
}
###
POST http://localhost:3001/api/blogs
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR5bmFtb0BnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjg0NDM2NjI2LCJleHAiOjE2ODQ0NDAyMjZ9.X4-0e4VNZTsZAVndV4ux_kUyhjq6hJRE3PrL_S7kabM
content-type: application/json

{
    "author":"elias hietanen",
    "url":"www.blogzzz.com",
    "title":"docker and kubernetes",
    "likes":12,
    "year_written": 2001
}