POST http://localhost:3001/api/blogs
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR5bmFtbyIsImlkIjoxLCJpYXQiOjE2ODQzNjEyNTYsImV4cCI6MTY4NDM2NDg1Nn0.DI5vOQ2tyxO3AcYAOW_0XTF1GdCd8RIAPBrBCjmlFKA
content-type: application/json

{
    "author":"elias hietanen",
    "url":"www.blogworld.com",
    "title":"crazy new blog",
    "likes":3
}